server:
  port: 8011

spring:
  datasource:
    url: ${DATABASE_URL}
    #DATABASE_URL=jdbc:postgresql://localhost:5432/config-db
    #DATABASE_PASSWORD=bcb@1234
    username: postgres
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#SPRING_DATASOURCE_PASSWORD=bcb@1234 /Deadpool2024BBH
#SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/employee_db
#SPRING_DATASOURCE_USERNAME=postgres
# Employee performance traking app

# revert example
